Updated documentation
TASRobotics/RaidZero-Outreach-Swerve-Docs pull request #1
Opened 2022-12-06 09:08 UTC by 0x5b62656e5d

2022-12-06 09:57 UTC, jazonshou requested changes
Overall, very nice progress; keep up the good work!

2022-12-06 09:57 UTC, jazonshou commented on source/Docs/Software/SwerveModuleClass.rst
> +Private Members
Call it "Instance Variables"

2022-12-06 09:57 UTC, jazonshou commented on source/Docs/Software/SwerveModuleClass.rst
> +========
Also another thing, the number of "=" or "*" or "-" needs to be equal to the number of characters in your subtitle

2022-12-06 22:47 UTC, 0x5b62656e5d commented on source/Docs/Software/SwerveModuleClass.rst
> +========
> After this, put all of the configuration in 1 code block, it'll make more sense soon (but basically different motors use different methods to initialize and we want to add different code for different motors... putting everything in 1 code block just makes it more concise for the reader)

Do I just put the whole config code in one block then depict it section by section?

2022-12-07 00:20 UTC, jazonshou commented on source/Docs/Software/SwerveModuleClass.rst
> +========
Yeah, 1 block & comments

2022-12-07 01:39 UTC, 0x5b62656e5d commented on source/Docs/Software/SwerveModuleClass.rst
> +========
> Yeah, 1 block & comments in the code

something like this?
![image](https://user-images.githubusercontent.com/112295217/206066594-2f756092-2cc0-4a21-a4f0-561940c2cb8d.png)

2022-12-07 09:26 UTC, jazonshou commented on source/Docs/Software/SwerveModuleClass.rst
> +========
yes

2022-12-07 10:02 UTC, 0x5b62656e5d commented on source/Docs/Software/SwerveModuleClass.rst
> +========
Just curious why not do the documentation by blocks? (the current format i have rn, u can check I pushed to branch)

2022-12-07 10:09 UTC, jazonshou requested changes
good job with the changes, just a few more details

the reason why I want the entire constructor in 1 code block is that different types of electronics will use different methods in the constructor. this just makes it easier for me to add the different code later on.

2022-12-07 10:09 UTC, jazonshou commented on build/html/_sources/Docs/Software/SwerveModuleClass.rst.txt
> +==============================
```suggestion
Instantiate Instance Variables
==============================

```

2022-12-07 10:09 UTC, jazonshou commented on build/html/_sources/Docs/Software/SwerveModuleClass.rst.txt
> +4. Sets neutral mode for throttle (Coast/Brake)
everything here should be under the same code block

for explanations, just add comments into the code

for explaining the parameters of the constructor, just have a comment block

2022-12-07 10:10 UTC, jazonshou commented on source/Docs/Software/SwerveModuleClass.rst
> +========
wdym by blocks

2022-12-10 10:03 UTC, jazonshou approved these changes
seems okay for now, ill make some changes

2022-12-10 10:03 UTC, merged