Swerve Class documentation
TASRobotics/RaidZero-Outreach-Swerve-Docs pull request #2
Opened 2022-12-11 09:46 UTC by 0x5b62656e5d

2022-12-11 09:46 UTC, 0x5b62656e5d commented
Links will need to be updated; WPI API is down

2022-12-11 10:27 UTC, jazonshou requested changes
Good job so far, try to work on these suggestions for now. I'll look at it more later

2022-12-11 10:27 UTC, jazonshou commented on source/Docs/Software/SwerveClass.rst
> +##################
```suggestion
############
Swerve Class
############
```

2022-12-11 10:27 UTC, jazonshou commented on source/Docs/Software/SwerveClass.rst
> +==============
```suggestion
IMU Selection
=============
```

2022-12-11 10:27 UTC, jazonshou commented on source/Docs/Software/SwerveClass.rst
> +and a 3 axis magnetometer to measure the magnetic waves around it. A WPI_Pigeon2 controller is used to call methods to get the values from this sensor.
basically there are a lot more IMUs in FRC than just the pigeon 2. then list common choices of IMUs: Pigeon2, navX2, PigeonIMU, navX. make sure to include links to their API & product pages

2022-12-11 10:27 UTC, jazonshou commented on source/Docs/Software/SwerveClass.rst
> +===============
```suggestion
===========
```

2022-12-11 10:27 UTC, jazonshou commented on source/Docs/Software/SwerveClass.rst
> +    // Initializes odometry
```suggestion
    
    // Initializes odometry
```

2022-12-11 10:27 UTC, jazonshou commented on source/Docs/Software/SwerveClass.rst
> +        // First set it at zero, look at offset, then change
```suggestion

```

2022-12-11 10:27 UTC, jazonshou commented on source/Docs/Software/SwerveClass.rst
> +
periodic shouldn't be rly considered as a method, maybe move it out of the method subcategory

2022-12-14 00:45 UTC, jazonshou requested changes

2022-12-14 00:45 UTC, jazonshou commented on source/Docs/Software/SwerveClass.rst
> +and a 3 axis magnetometer to measure the magnetic waves around it. A WPI_Pigeon2 controller is used to call methods to get the values from this sensor.
You dont need all this extra info - just specify that it's an imu & it measures angle of the robot

also specify that pigeon2 will be used in the docs

2022-12-22 02:59 UTC, jazonshou approved these changes

2022-12-22 02:59 UTC, merged