Updated Teleop documentation
TASRobotics/RaidZero-Outreach-Swerve-Docs pull request #3
Opened 2022-12-26 07:40 UTC by 0x5b62656e5d

2022-12-26 07:40 UTC, 0x5b62656e5d commented
Still have to figure out how to embed a youtube video in rst
`.. youtube::` doesnt work

2022-12-26 14:07 UTC, jazonshou requested changes
Pretty good so far, the content is mostly there. Just a few suggestions on how you could format things clearer.

2022-12-26 14:07 UTC, jazonshou commented on source/Docs/Software/TeleOp.rst
> +Here's an example of a `swerve drive <https://www.youtube.com/watch?v=50ZRrYFWPIc&ab_channel=FirstUpdatesNow>`_ and how it's controlled.
Perhaps you could make a table to compare field oriented & robot oriented drive

also the video specifically demonstrates field oriented control, so you'll need to specify that

and use this link instead: https://youtu.be/50ZRrYFWPIc?t=21
cuz it starts the video at the field oriented control part

2022-12-26 14:07 UTC, jazonshou commented on source/Docs/Software/TeleOp.rst
> +It indicates the operation of a system or machine at a distance. This documentation will be referring to the manual drive class, and specific parts of the RobotContainer class.
you dont need to specify this stuff, teams should go in understanding what teleop is. though you can make it clearer by saying that it will be what the robot runs during the 2 minutes and 15 seconds of manual driver control

2022-12-26 14:07 UTC, jazonshou commented on source/Docs/Software/TeleOp.rst
> +Here's an example of a `swerve drive <https://www.youtube.com/watch?v=50ZRrYFWPIc&ab_channel=FirstUpdatesNow>`_ and how it's controlled.
but in general, you have the right ideas written. i just think that it'll be clearer if you put it into a table

2022-12-26 14:07 UTC, jazonshou commented on source/Docs/Software/TeleOp.rst
> +    // Initializes Swerve object
```suggestion
    // Initializes Swerve object
    private final Swerve mSwerve;
```
always put comments above the code

2022-12-26 14:07 UTC, jazonshou commented on source/Docs/Software/TeleOp.rst
> +
comment/code formatting applies here too

2022-12-26 14:07 UTC, jazonshou commented on source/Docs/Software/TeleOp.rst
> +        // True/false for field oriented driving
comment/code formatting, see above

2022-12-26 14:07 UTC, jazonshou commented on source/Docs/Software/TeleOp.rst
> +===========
make sure to specify how you need to first create a command, and then call the command in robot container

also specify that the constructor creates the command, which will be used in robot container

2022-12-26 14:07 UTC, jazonshou commented on source/Docs/Software/TeleOp.rst
> +===========
maybe you can make this whole section like "Drive Command" or something like that

and then your next section can be something like "Calling Drive Command" which discusses using the command in robotcontainer

2022-12-26 14:07 UTC, jazonshou commented on source/Docs/Software/TeleOp.rst
> +    }
comment/code formatting

2022-12-27 02:51 UTC, 0x5b62656e5d commented
> Still have to figure out how to embed a youtube video in rst `.. youtube::` doesnt work

Used raw html embed

2022-12-27 13:03 UTC, jazonshou approved these changes
seems good, might make a few structure changes just for looks though

2022-12-27 13:10 UTC, merged